# Refer to utils/config.py for definition and options.
version = "SparseMat"

[model]
dilation_kernel = 15
max_n_pixel = 4000000

[loss]
alpha_loss_weights = [0.1, 0.1, 0.1, 1.0]
with_composition_loss = true
composition_loss_weight = 0.5

[train]
batch_size = 12
epoch = 30
epoch_decay = 10
lr = 0.0001
min_lr = 0.00001
adaptive_lr = true
beta1 = 0.9
beta2 = 0.999
pretrained_model = "pretrained/lpn.pth"
num_workers = 16

[aug]
rescale_size = 560
crop_size = 512
patch_crop_size = [512, 640, 800]
patch_load_size = 512

[data]
dataset = "HHM50K"
filelist_train = "data/HHM50K.txt"
filelist_val = "data/HHM2K.txt"
filelist_test = "data/HHM2K.txt"

[log]
save_frq = 50

[test]
batch_size = 1
rescale_size = 512
patch_size = 512
max_size = 7680
save = true
cascade = true
checkpoint = "pretrained/SparseMat.pth"
save_dir = "predictions/SparseMatte/HHM2K"
